name: dev ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: [self-hosted, linux]
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    # services:
    #   postgres:
    #     image: postgres:12.2-alpine
    #     env:
    #       POSTGRES_USER: runner
    #       POSTGRES_PASSWORD: runner
    #       POSTGRES_DB: unittest
    #     ports:
    #       - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Lint
        run: |
          ./gradlew ktlintCheck

      - name: Unit test
        run: ./gradlew test -i

      - name: Coverage
        run: ./gradlew jacocoTestReport

      - name: Build jar
        run: ./gradlew installDist

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/install/dynamic-catalog-service

  package_docker:
    runs-on: [self-hosted, linux]
    needs:
      - build_test
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Docker image name env
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "GITLAB_IMAGE_NAME=registry.gitlab.com/target-digital-transformation/df/dynamic-catalog-service/github:${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build docker image
        # permission change due to: actions/upload-artifact#38
        run: |
          ls -R
          docker build -f- -t $IMAGE_NAME . <<EOF
          FROM registry.tespkg.in/library/openjdk:8-jre-slim
          LABEL org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}
          COPY . /usr/local/dynamic-catalog-service
          WORKDIR /usr/local/dynamic-catalog-service
          CMD ["/usr/local/dynamic-catalog-service/bin/dynamic-catalog-service", "serve"]
          EOF

      - name: Push image to github container registry
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USER }} --password-stdin
          docker push $IMAGE_NAME

      - name: Push image to gitlab registry
        run: |
          echo ${{ secrets.GITLAB_CR_PAT }} | docker login registry.gitlab.com -u ${{ secrets.GITLAB_CR_USER }} --password-stdin
          docker tag $IMAGE_NAME $GITLAB_IMAGE_NAME
          docker push $GITLAB_IMAGE_NAME

  deploy_to_dev:
    runs-on: [self-hosted, linux]
    needs:
      - package_docker
    steps:
      - name: Push to ArgoCD
        run: |
          echo "TODO"
          echo "$IMAGE_NAME"
          echo "$GITLAB_IMAGE_NAME"
          echo ${{ env.IMAGE_NAME }}
          echo ${{ env.GITLAB_IMAGE_NAME }}
